# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.create(location: "Auckland")
Location.create(location: "Devonport")
Location.create(location: "Waiuku")
Location.create(location: "Rotorua")
Location.create(location: "Tauranga")
Location.create(location: "Akaroa")
Location.create(location: "Christchurch")
Location.create(location: "Lyttelton")
Location.create(location: "Timaru")
Location.create(location: "Gisborne")
Location.create(location: "Hastings")
Location.create(location: "Napier")
Location.create(location: "Pahiatua")
Location.create(location: "Palmerston North")
Location.create(location: "Taihape")
Location.create(location: "Wanganui")
Location.create(location: "Blenheim")
Location.create(location: "Picton")
Location.create(location: "Nelson")
Location.create(location: "Kaitaia")
Location.create(location: "Russell")
Location.create(location: "Alexandra")
Location.create(location: "Dunedin")
Location.create(location: "Kaitangata")
Location.create(location: "Oamaru")
Location.create(location: "Invercargill")
Location.create(location: "Hawera")
Location.create(location: "Kapuni")
Location.create(location: "New Plymouth")
Location.create(location: "Stratford")
Location.create(location: "Hamilton")
Location.create(location: "Paeroa")
Location.create(location: "Te Aroha")
Location.create(location: "Tokoroa")
Location.create(location: "Waihi")
Location.create(location: "Lower Hutt")
Location.create(location: "Masterton")
Location.create(location: "Porirua")
Location.create(location: "Upper Hutt")
Location.create(location: "Wellington")
Location.create(location: "Greymouth")
Location.create(location: "Hokitika")
Location.create(location: "Westport")

Manufacturer.create(manufacturer: "Aprilia")
Manufacturer.create(manufacturer: "Benelli")
Manufacturer.create(manufacturer: "Bimota")
Manufacturer.create(manufacturer: "BMW")
Manufacturer.create(manufacturer: "Ducati")
Manufacturer.create(manufacturer: "Harley Davidson")
Manufacturer.create(manufacturer: "Honda")
Manufacturer.create(manufacturer: "Husqvarna")
Manufacturer.create(manufacturer: "Indian")
Manufacturer.create(manufacturer: "Kawasaki")
Manufacturer.create(manufacturer: "KTM")
Manufacturer.create(manufacturer: "Moto Guzzi")
Manufacturer.create(manufacturer: "MV Agusta")
Manufacturer.create(manufacturer: "Piaggio")
Manufacturer.create(manufacturer: "Royal Enfield")
Manufacturer.create(manufacturer: "Suzuki")
Manufacturer.create(manufacturer: "Triumph")
Manufacturer.create(manufacturer: "Yamaha")
Manufacturer.create(manufacturer: "Other")

Style.create(style: "Adventure")
Style.create(style: "Cafe Racer")
Style.create(style: "Cruiser")
Style.create(style: "Commuter")
Style.create(style: "Classic")
Style.create(style: "Dirt bikes")
Style.create(style: "Dual sport")
Style.create(style: "Naked")
Style.create(style: "Sport")
Style.create(style: "Sports Tourer")
Style.create(style: "Tourer")
Style.create(style: "Trials")
Style.create(style: "Scooter")
Style.create(style: "Supermoto")